// Code generated by prismic-ts-codegen. DO NOT EDIT.
import type * as prismicT from '@prismicio/types';

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Category of project documents */
interface CategoryOfProjectDocumentData {
    /**
     * Title field in *Category of project*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Category title
     * - **API ID Path**: category_of_project.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Type of category field in *Category of project*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Work
     * - **API ID Path**: category_of_project.type_of_category
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    type_of_category: prismicT.SelectField<'Work' | 'Segment', 'filled'>;
}
/**
 * Category of project document from Prismic
 *
 * - **API ID**: `category_of_project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryOfProjectDocument<Lang extends string = string> =
    prismicT.PrismicDocumentWithoutUID<
        Simplify<CategoryOfProjectDocumentData>,
        'category_of_project',
        Lang
    >;
/** Content for Project Card documents */
interface ProjectCardDocumentData {
    /**
     * Poster field in *Project Card*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project-card.poster
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    poster: prismicT.ImageField<never>;
    /**
     * Title field in *Project Card*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Project title ( Project name )
     * - **API ID Path**: project-card.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Categories field in *Project Card*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: project-card.categories[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    categories: prismicT.GroupField<Simplify<ProjectCardDocumentDataCategoriesItem>>;
    /**
     * Slice zone field in *Project Card*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: project-card.body[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    body: prismicT.SliceZone<ProjectCardDocumentDataBodySlice>;
}
/**
 * Item in Project Card → Categories
 *
 */
export interface ProjectCardDocumentDataCategoriesItem {
    /**
     * Category field in *Project Card → Categories*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: project-card.categories[].category1
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    category1: prismicT.RelationField<'category_of_project'>;
}
/**
 * Primary content in Project Card → Slice zone → `hero_banner` → Primary
 *
 */
interface ProjectCardDocumentDataBodyHeroBannerSlicePrimary {
    /**
     * Background image field in *Project Card → Slice zone → `hero_banner` → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project-card.body[].hero_banner.primary.background_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    background_image: prismicT.ImageField<never>;
    /**
     * Link field in *Project Card → Slice zone → `hero_banner` → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Link to project
     * - **API ID Path**: project-card.body[].hero_banner.primary.link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
export type ProjectCardDocumentDataBodyHeroBannerSlice = prismicT.Slice<
    'hero_banner',
    Simplify<ProjectCardDocumentDataBodyHeroBannerSlicePrimary>,
    never
>;
/**
 * Primary content in Project Card → Slice zone → `intro` → Primary
 *
 */
interface ProjectCardDocumentDataBodyIntroSlicePrimary {
    /**
     * Background image field in *Project Card → Slice zone → `intro` → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project-card.body[].intro.primary.background_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    background_image: prismicT.ImageField<never>;
    /**
     * Preview on devices field in *Project Card → Slice zone → `intro` → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project-card.body[].intro.primary.preview_on_devices
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    preview_on_devices: prismicT.ImageField<never>;
    /**
     * Logo field in *Project Card → Slice zone → `intro` → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project-card.body[].intro.primary.logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * Description field in *Project Card → Slice zone → `intro` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Small description
     * - **API ID Path**: project-card.body[].intro.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
export type ProjectCardDocumentDataBodyIntroSlice = prismicT.Slice<
    'intro',
    Simplify<ProjectCardDocumentDataBodyIntroSlicePrimary>,
    never
>;
/**
 * Primary content in Project Card → Slice zone → `business` → Primary
 *
 */
interface ProjectCardDocumentDataBodyBusinessSlicePrimary {
    /**
     * Description field in *Project Card → Slice zone → `business` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Small description
     * - **API ID Path**: project-card.body[].business.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Wireframe field in *Project Card → Slice zone → `business` → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project-card.body[].business.primary.wireframe
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    wireframe: prismicT.ImageField<never>;
}
export type ProjectCardDocumentDataBodyBusinessSlice = prismicT.Slice<
    'business',
    Simplify<ProjectCardDocumentDataBodyBusinessSlicePrimary>,
    never
>;
/**
 * Item in Project Card → Slice zone → `solution` → Items
 *
 */
export interface ProjectCardDocumentDataBodySolutionSliceItem {
    /**
     * Specialists field in *Project Card → Slice zone → `solution` → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Amount and type of specialist
     * - **API ID Path**: project-card.body[].solution.items[].specialists
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    specialists: prismicT.TitleField;
}
export type ProjectCardDocumentDataBodySolutionSlice = prismicT.Slice<
    'solution',
    Record<string, never>,
    Simplify<ProjectCardDocumentDataBodySolutionSliceItem>
>;
/**
 * Primary content in Project Card → Slice zone → `branding_slider` → Primary
 *
 */
interface ProjectCardDocumentDataBodyBrandingSliderSlicePrimary {
    /**
     * Background cover field in *Project Card → Slice zone → `branding_slider` → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project-card.body[].branding_slider.primary.background_cover
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    background_cover: prismicT.ImageField<never>;
}
/**
 * Item in Project Card → Slice zone → `branding_slider` → Items
 *
 */
export interface ProjectCardDocumentDataBodyBrandingSliderSliceItem {
    /**
     * Slides field in *Project Card → Slice zone → `branding_slider` → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project-card.body[].branding_slider.items[].slides
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    slides: prismicT.ImageField<never>;
    /**
     * Branding list field in *Project Card → Slice zone → `branding_slider` → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: What was done ( Logo development, ad materials...)
     * - **API ID Path**: project-card.body[].branding_slider.items[].branding_list
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    branding_list: prismicT.TitleField;
}
export type ProjectCardDocumentDataBodyBrandingSliderSlice = prismicT.Slice<
    'branding_slider',
    Simplify<ProjectCardDocumentDataBodyBrandingSliderSlicePrimary>,
    Simplify<ProjectCardDocumentDataBodyBrandingSliderSliceItem>
>;
/**
 * Primary content in Project Card → Slice zone → `design_stage` → Primary
 *
 */
interface ProjectCardDocumentDataBodyDesignStageSlicePrimary {
    /**
     * Description field in *Project Card → Slice zone → `design_stage` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Small description
     * - **API ID Path**: project-card.body[].design_stage.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Wireframe image field in *Project Card → Slice zone → `design_stage` → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project-card.body[].design_stage.primary.wireframe_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    wireframe_image: prismicT.ImageField<never>;
}
export type ProjectCardDocumentDataBodyDesignStageSlice = prismicT.Slice<
    'design_stage',
    Simplify<ProjectCardDocumentDataBodyDesignStageSlicePrimary>,
    never
>;
/**
 * Primary content in Project Card → Slice zone → `figma_design` → Primary
 *
 */
interface ProjectCardDocumentDataBodyFigmaDesignSlicePrimary {
    /**
     * Cover image field in *Project Card → Slice zone → `figma_design` → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project-card.body[].figma_design.primary.cover_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover_image: prismicT.ImageField<never>;
}
export type ProjectCardDocumentDataBodyFigmaDesignSlice = prismicT.Slice<
    'figma_design',
    Simplify<ProjectCardDocumentDataBodyFigmaDesignSlicePrimary>,
    never
>;
/**
 * Primary content in Project Card → Slice zone → `uikit` → Primary
 *
 */
interface ProjectCardDocumentDataBodyUikitSlicePrimary {
    /**
     * Description field in *Project Card → Slice zone → `uikit` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Small description
     * - **API ID Path**: project-card.body[].uikit.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in Project Card → Slice zone → `uikit` → Items
 *
 */
export interface ProjectCardDocumentDataBodyUikitSliceItem {
    /**
     * ui kit slide field in *Project Card → Slice zone → `uikit` → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project-card.body[].uikit.items[].ui_kit_slide
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    ui_kit_slide: prismicT.ImageField<never>;
}
export type ProjectCardDocumentDataBodyUikitSlice = prismicT.Slice<
    'uikit',
    Simplify<ProjectCardDocumentDataBodyUikitSlicePrimary>,
    Simplify<ProjectCardDocumentDataBodyUikitSliceItem>
>;
/**
 * Primary content in Project Card → Slice zone → `final_result` → Primary
 *
 */
interface ProjectCardDocumentDataBodyFinalResultSlicePrimary {
    /**
     * Cover image field in *Project Card → Slice zone → `final_result` → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project-card.body[].final_result.primary.cover_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover_image: prismicT.ImageField<never>;
}
export type ProjectCardDocumentDataBodyFinalResultSlice = prismicT.Slice<
    'final_result',
    Simplify<ProjectCardDocumentDataBodyFinalResultSlicePrimary>,
    never
>;
/**
 * Item in Project Card → Slice zone → `full_block_slider` → Items
 *
 */
export interface ProjectCardDocumentDataBodyFullBlockSliderSliceItem {
    /**
     * Result slide field in *Project Card → Slice zone → `full_block_slider` → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project-card.body[].full_block_slider.items[].result_slide
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    result_slide: prismicT.ImageField<never>;
}
export type ProjectCardDocumentDataBodyFullBlockSliderSlice = prismicT.Slice<
    'full_block_slider',
    Record<string, never>,
    Simplify<ProjectCardDocumentDataBodyFullBlockSliderSliceItem>
>;
/**
 * Item in Project Card → Slice zone → `solution_specialists` → Items
 *
 */
export interface ProjectCardDocumentDataBodySolutionSpecialistsSliceItem {
    /**
     * Technologies field in *Project Card → Slice zone → `solution_specialists` → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Tech stack used
     * - **API ID Path**: project-card.body[].solution_specialists.items[].technologies
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    technologies: prismicT.TitleField;
}
export type ProjectCardDocumentDataBodySolutionSpecialistsSlice = prismicT.Slice<
    'solution_specialists',
    Record<string, never>,
    Simplify<ProjectCardDocumentDataBodySolutionSpecialistsSliceItem>
>;
/**
 * Item in Project Card → Slice zone → `branding_list` → Items
 *
 */
export interface ProjectCardDocumentDataBodyBrandingListSliceItem {
    /**
     * Branding list item field in *Project Card → Slice zone → `branding_list` → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: ( Logo development, ad materials...)
     * - **API ID Path**: project-card.body[].branding_list.items[].branding_list_item
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    branding_list_item: prismicT.TitleField;
}
export type ProjectCardDocumentDataBodyBrandingListSlice = prismicT.Slice<
    'branding_list',
    Record<string, never>,
    Simplify<ProjectCardDocumentDataBodyBrandingListSliceItem>
>;
/**
 * Item in Project Card → Slice zone → `final_result_works_done` → Items
 *
 */
export interface ProjectCardDocumentDataBodyFinalResultWorksDoneSliceItem {
    /**
     * Works done field in *Project Card → Slice zone → `final_result_works_done` → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: project-card.body[].final_result_works_done.items[].works_done
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    works_done: prismicT.TitleField;
}
export type ProjectCardDocumentDataBodyFinalResultWorksDoneSlice = prismicT.Slice<
    'final_result_works_done',
    Record<string, never>,
    Simplify<ProjectCardDocumentDataBodyFinalResultWorksDoneSliceItem>
>;
/**
 * Item in Project Card → Slice zone → `final_result_achievements` → Items
 *
 */
export interface ProjectCardDocumentDataBodyFinalResultAchievementsSliceItem {
    /**
     * Achievements field in *Project Card → Slice zone → `final_result_achievements` → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: project-card.body[].final_result_achievements.items[].achievements
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    achievements: prismicT.TitleField;
}
export type ProjectCardDocumentDataBodyFinalResultAchievementsSlice = prismicT.Slice<
    'final_result_achievements',
    Record<string, never>,
    Simplify<ProjectCardDocumentDataBodyFinalResultAchievementsSliceItem>
>;
/**
 * Slice for *Project Card → Slice zone*
 *
 */
type ProjectCardDocumentDataBodySlice =
    | ProjectCardDocumentDataBodyHeroBannerSlice
    | ProjectCardDocumentDataBodyIntroSlice
    | ProjectCardDocumentDataBodyBusinessSlice
    | ProjectCardDocumentDataBodySolutionSlice
    | ProjectCardDocumentDataBodyBrandingSliderSlice
    | ProjectCardDocumentDataBodyDesignStageSlice
    | ProjectCardDocumentDataBodyFigmaDesignSlice
    | ProjectCardDocumentDataBodyUikitSlice
    | ProjectCardDocumentDataBodyFinalResultSlice
    | ProjectCardDocumentDataBodyFullBlockSliderSlice
    | ProjectCardDocumentDataBodySolutionSpecialistsSlice
    | ProjectCardDocumentDataBodyBrandingListSlice
    | ProjectCardDocumentDataBodyFinalResultWorksDoneSlice
    | ProjectCardDocumentDataBodyFinalResultAchievementsSlice;
/**
 * Project Card document from Prismic
 *
 * - **API ID**: `project-card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectCardDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<
    Simplify<ProjectCardDocumentData>,
    'project-card',
    Lang
>;
export type AllDocumentTypes = CategoryOfProjectDocument | ProjectCardDocument;
declare module '@prismicio/client' {
    namespace Content {
        export type {
            CategoryOfProjectDocumentData,
            CategoryOfProjectDocument,
            ProjectCardDocumentData,
            ProjectCardDocumentDataCategoriesItem,
            ProjectCardDocumentDataBodyHeroBannerSlicePrimary,
            ProjectCardDocumentDataBodyHeroBannerSlice,
            ProjectCardDocumentDataBodyIntroSlicePrimary,
            ProjectCardDocumentDataBodyIntroSlice,
            ProjectCardDocumentDataBodyBusinessSlicePrimary,
            ProjectCardDocumentDataBodyBusinessSlice,
            ProjectCardDocumentDataBodySolutionSliceItem,
            ProjectCardDocumentDataBodySolutionSlice,
            ProjectCardDocumentDataBodyBrandingSliderSlicePrimary,
            ProjectCardDocumentDataBodyBrandingSliderSliceItem,
            ProjectCardDocumentDataBodyBrandingSliderSlice,
            ProjectCardDocumentDataBodyDesignStageSlicePrimary,
            ProjectCardDocumentDataBodyDesignStageSlice,
            ProjectCardDocumentDataBodyFigmaDesignSlicePrimary,
            ProjectCardDocumentDataBodyFigmaDesignSlice,
            ProjectCardDocumentDataBodyUikitSlicePrimary,
            ProjectCardDocumentDataBodyUikitSliceItem,
            ProjectCardDocumentDataBodyUikitSlice,
            ProjectCardDocumentDataBodyFinalResultSlicePrimary,
            ProjectCardDocumentDataBodyFinalResultSlice,
            ProjectCardDocumentDataBodyFullBlockSliderSliceItem,
            ProjectCardDocumentDataBodyFullBlockSliderSlice,
            ProjectCardDocumentDataBodySolutionSpecialistsSliceItem,
            ProjectCardDocumentDataBodySolutionSpecialistsSlice,
            ProjectCardDocumentDataBodyBrandingListSliceItem,
            ProjectCardDocumentDataBodyBrandingListSlice,
            ProjectCardDocumentDataBodyFinalResultWorksDoneSliceItem,
            ProjectCardDocumentDataBodyFinalResultWorksDoneSlice,
            ProjectCardDocumentDataBodyFinalResultAchievementsSliceItem,
            ProjectCardDocumentDataBodyFinalResultAchievementsSlice,
            ProjectCardDocumentDataBodySlice,
            ProjectCardDocument,
            AllDocumentTypes,
        };
    }
}
